name: Push verifications
on:
  - push
jobs:
  build_and_deploy:
    runs-on: ubuntu-22.04
    env:
      IMAGE_NAME: "deploy-api"
      DOCKER_USERNAME: "loancb"
      DOCKER_NAME: "ci-cd-eval"
    steps:
      - name: Checkout on branch
        uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./Dockerfile

      - name: Build project image
        run: docker image build --tag="${IMAGE_NAME}" ./

      - name: Lint, build and run test
        run: docker container run "${IMAGE_NAME}" npm run lint && npm run build && npm run test

      - name: Login to Docker Hub
        if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: "${DOCKER_USERNAME}"
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push release image to docker hub
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./
          tags: "${DOCKER_USERNAME}/${DOCKER_NAME}:${{ github.ref_name }}"

      - name: Push unstable release to docker hub
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./
          tags: "${DOCKER_USERNAME}/${DOCKER_NAME}:unstable"
